default_stages: [pre-commit]
repos:
  - repo: local
    hooks:
      - id: actionlint
        name: actionlint
        entry: actionlint
        files: ^.github/workflows/
        types: [yaml]
        language: system
