name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Flake Check
        run: nix flake check

      - name: Setup & Build
        run: nix develop --command just setup build

      - name: Full Check
        run: nix develop --command just check
